//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HomeSlider> HomeSliders { get; set; }
        public virtual DbSet<HomeCollection> HomeCollections { get; set; }
        public virtual DbSet<HomeComingProduct> HomeComingProducts { get; set; }
        public virtual DbSet<HomeFeaturedProduct> HomeFeaturedProducts { get; set; }
        public virtual DbSet<Smartphone> Smartphones { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<AdminAccount> AdminAccounts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderSubmit> OrderSubmits { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
