//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeCollection
    {
        public int Id { get; set; }
        public string LeftImage { get; set; }
        public string CenterImage { get; set; }
        public string RightImage { get; set; }
        public string FirstTextMain { get; set; }
        public string FirstTextInfo { get; set; }
        public string SecondTextMain { get; set; }
        public string SecondTextInfo { get; set; }
    }
}
