//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string TitleTop { get; set; }
        public string TitleMain { get; set; }
        public string TitleBottom { get; set; }
        public string TitleSpan { get; set; }
    }
}
