//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeComingProduct
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> NewPrice { get; set; }
        public Nullable<decimal> PrevPrice { get; set; }
        public string Info { get; set; }
        public string Brand { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Color3 { get; set; }
        public string Memory { get; set; }
        public string Camera { get; set; }
    }
}
